name:               "Multi-Media Lab"
title:              "Multi-Media Lab"
description:        "Multi-Media Lab"

url:                https://mmdclab.github.io
baseurl:      

markdown: kramdown

tracking_id: #

footer: yes
footer_text: "School of Computer Science and Technology at Xi'an JiaoTong University<br>No.28, West Xianning Road, Xi'an, Shaanxi, 710049"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "Publications"
   link: "/publications/"
 - name: "People"
   link: "/people/"
 - name: "Seminars"
   link: "/seminars/"

collections:
  people:
    output: true
    permalink: /people/:title/index.html